name: seleniumTest run

on:
  workflow_dispatch:
    inputs:
      applicationUnderTest:
        description: 'Select application'
        required: true
        default: amazon
        type: choice
        options:
          - amazon
          - flipkart

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: jagadeesh-nj/newProjectchandu
          token: ${{ secrets.PAT_TOKEN }}

      - name: Setup Java (with Maven cache)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Clear WebDriver cache
        run: rm -rf ~/.cache/selenium  
      - name: Clean build
        run: mvn clean install -U
